dbt2:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: SNOWFLAKE_LEARNING_WH
      database: SNOWFLAKE_LEARNING_DB
      schema: DVERVARCKE_LOAD_SAMPLE_DATA_FROM_S3
